### ISSUE TITLE
【依頼】挙動確認

### ISSUE THREAD

**Issue by nyuristen** [nyuristen/chat-space#15]
#IPアドレス
　18.182.175.69

**Comment by kohei-isoda** [comment]
成田さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**◯ 一度サイドバーのリンクを踏むと文字が紫になり見づらい（白で固定してください）**
[![Screenshot from Gyazo](https://gyazo.com/c8e4fb3dedfff8eec562bd3aa12bb07b/raw)](https://gyazo.com/c8e4fb3dedfff8eec562bd3aa12bb07b)

**◯ メッセージを投稿すると投稿日時がundefinedで表示される**

**◯ グループ編集で所属しているメンバーが表示されず、編集（削除）することが出来ない**

**◯ フラッシュメッセージが固定されていない**
[![Screenshot from Gyazo](https://gyazo.com/c14eabe8cf9d28b891fded5f7ba1791e/raw)](https://gyazo.com/c14eabe8cf9d28b891fded5f7ba1791e)

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by naru6117** [comment]
成田さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**・自動更新の際に日時の表示が「undefined」になってしまう**
　[![Screenshot from Gyazo](https://gyazo.com/4a763f18ed8d223c23c1011bee77d496/raw)](https://gyazo.com/4a763f18ed8d223c23c1011bee77d496)


修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたので**LGTMと**させて頂きます🎉
おめでとうございます！
